name: build
on: [push, pull_request]

jobs:
  master-qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Lint
        run: ./gradlew lintMasterQa

      - name: Unit Test
        run: ./gradlew testMasterQaUnitTest

      - name: Build APK
        run: ./gradlew assembleMasterQa

      - name: Upload reports to artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: master-qa reports
          path: ./app/build/reports/

  internal-qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Lint
        env:
          NUMBERS_STORAGE_BASE_URL: ${{ secrets.NUMBERS_STORAGE_BASE_URL }}
        run: ./gradlew lintInternalQa

      - name: Unit Test
        env:
          NUMBERS_STORAGE_BASE_URL: ${{ secrets.NUMBERS_STORAGE_BASE_URL }}
        run: ./gradlew testInternalQaUnitTest

      - name: Build APK
        env:
          NUMBERS_STORAGE_BASE_URL: ${{ secrets.NUMBERS_STORAGE_BASE_URL }}
        run: ./gradlew assembleInternalQa

      - name: Upload reports to artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: internal-qa reports
          path: ./app/build/reports/

  util-verification:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./util/verification/
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          echo "PATH=$HOME/.poetry/bin:$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: poetry install --no-root

      - name: Lint
        run: |
          poetry run python -m pylint verification/
          poetry run python -m mypy --ignore-missing-import verification/

      - name: Test
        run: poetry run python -m pytest -v