name: upload-drive
on: workflow_dispatch

jobs:
  upload-drive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build APKs
        env:
          NUMBERS_STORAGE_BASE_URL: ${{ secrets.NUMBERS_STORAGE_BASE_URL }}
        run: |
          ./gradlew assembleMasterDebug
          ./gradlew assembleMasterQa
          ./gradlew assembleInternalDebug
          ./gradlew assembleInternalQa

      - name: Extract app version
        id: extract_version
        run: |
          echo "::set-output name=versionCode::$(./gradlew -q printVersionCode)"
          echo "::set-output name=versionName::$(./gradlew -q printVersionName)"

      - name: Upload master-debug outputs to Google Drive
        uses: satackey/action-google-drive@v1
        with:
          skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
          google-client-id: ${{ secrets.SKICKA_GOOGLE_CLIENT_ID }}
          google-client-secret: ${{ secrets.SKICKA_GOOGLE_CLIENT_SECRET }}
          upload-from: ./app/build/outputs/apk/master/debug/
          upload-to: /starling-capture/apk/master/debug/

      - name: Upload master-qa outputs to Google Drive
        uses: satackey/action-google-drive@v1
        with:
          skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
          google-client-id: ${{ secrets.SKICKA_GOOGLE_CLIENT_ID }}
          google-client-secret: ${{ secrets.SKICKA_GOOGLE_CLIENT_SECRET }}
          upload-from: ./app/build/outputs/apk/master/qa/
          upload-to: /starling-capture/apk/master/qa/

      - name: Upload internal-debug outputs to Google Drive
        uses: satackey/action-google-drive@v1
        with:
          skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
          google-client-id: ${{ secrets.SKICKA_GOOGLE_CLIENT_ID }}
          google-client-secret: ${{ secrets.SKICKA_GOOGLE_CLIENT_SECRET }}
          upload-from: ./app/build/outputs/apk/internal/debug/
          upload-to: /starling-capture/apk/internal/debug/

      - name: Upload internal-qa outputs to Google Drive
        uses: satackey/action-google-drive@v1
        with:
          skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
          google-client-id: ${{ secrets.SKICKA_GOOGLE_CLIENT_ID }}
          google-client-secret: ${{ secrets.SKICKA_GOOGLE_CLIENT_SECRET }}
          upload-from: ./app/build/outputs/apk/internal/qa/
          upload-to: /starling-capture/apk/internal/qa/